import { Check, KeyRound, LogIn, ShieldCheck } from "lucide-react";
import { BetaApplicationForm } from "@/components/beta-application-form";
import { SiteFooter, SiteHeader } from "@/components/marketing";

export default function StartPage() {
  return <main><SiteHeader />
    <section className="beta-application-hero"><div className="shell beta-application-hero-grid"><div><span className="kicker light">Founding adviser beta</span><h1>Help shape the engine—and keep the founding advantage.</h1><p>Fifteen individual Quilter advisers will receive free access throughout beta and 50% off their individual subscription for 12 months after launch.</p><div className="beta-application-benefits"><span><Check />No payment details</span><span><Check />Work directly with Daren</span><span><Check />Begin with a fictitious case</span></div></div><aside><ShieldCheck /><strong>Application only</strong><p>A founding place is confirmed personally after Daren understands your firm and workflow. Submitting this form does not create a contract or process a payment.</p></aside></div></section>
    <section className="section beta-form-section"><div className="shell beta-form-layout"><BetaApplicationForm /><aside className="beta-form-journey"><span>WHAT HAPPENS NEXT</span><h2>A supported route into the beta.</h2><ol><li><b>1</b><div><strong>Daren reviews the application</strong><p>A practical conversation about your firm and the work you most want to improve.</p></div></li><li><b>2</b><div><strong>Your founding place is confirmed</strong><p>Your Microsoft 365 work identity and firm onboarding route are agreed.</p></div></li><li><b>3</b><div><strong>Run the Test Drive</strong><p>Use a fictitious case before any live client workflow is considered.</p></div></li><li><b>4</b><div><strong>Start testing with support</strong><p>Challenge the workflows, report friction and help shape the launch version.</p></div></li></ol><div className="beta-existing-user"><KeyRound /><span><strong>Already approved?</strong>Use your existing Microsoft work account and MFA.</span><a href="https://app.theadviceengine.ai/"><LogIn />Sign in</a></div></aside></div></section>
    <SiteFooter /></main>;
}
